
#base00 = "1d2021" # ----
#base01 = "3c3836" # ---
#base02 = "504945" # --
#base03 = "665c54" # -
#base04 = "bdae93" # +
#base05 = "d5c4a1" # ++
#base06 = "ebdbb2" # +++
#base07 = "fbf1c7" # ++++
#base08 = "fb4934" # red
#base09 = "#fe8019" # orange
#base0A = "fabd2f" # yellow
#base0B = "b8bb26" # green
#base0C = "8ec07c" # aqua/cyan
#base0D = "83a598" # blue
#base0E = "d3869b" # purple
#base0F = "d65d0e" # brown

format = """
[](#665c54)\
\
$directory\
[](fg:#665c54 bg:#bdae93)\
$git_branch\
$git_status\
[ ](fg:#bdae93)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#665c54 fg:black"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#bdae93 fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#bdae93 fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#d5c4a1"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#d5c4a1 fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
